[sdl]
output=opengl
windowresolution=960x720
fullscreen=true

[dosbox]
title=Perceler
memsize=32

[cpu]
core=dynamic
cputype=pentium
cycles=max

[render]
aspect=true
scaler=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[midi]
mpu401=intelligent
mididevice=default

[dos]
xms=true
ems=true
umb=true

[autoexec]
@echo off
mount c ./build
c:
demo.exe
exit
