[sdl]
output=opengl
windowresolution=960x720
fullscreen=false

[dosbox]
title=Capturing...
memsize=32

[cpu]
core=dynamic
cycles=max
turbo=true

[render]
aspect=true
scaler=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[dos]
xms=true
ems=true
umb=true

[autoexec]
@echo off
mount c ./build
c:
set PERCELER_CAPTURE=CAPTURE
set PERCELER_RATE=44100
demo.exe
exit
