/*
 * Affine texture-mapped cube generated by polyhedron_create().
 * The marble texture's own palette is uploaded in init() so the
 * cube renders with the correct colours.
 */

#include "textured_cube.h"

#include "../assets.h"
#include "utils/font.h"
#include "utils/math.h"
#include "utils/model.h"
#include "utils/palette.h"
#include "utils/polyhedron.h"
#include "utils/render3d.h"

#include <stdlib.h>
#include <string.h>
#include <vga.h>

static const Camera3D camera = {
    INT_TO_FP(4),   /* cam_z */
    FP_ONE >> 2,    /* near_z */
    INT_TO_FP(220), /* proj_scale */
    160, 100        /* cx, cy */
};

static Model *cube;
static Texture *texture;
static int *transformed;        /* num_verts * 3 */
static int *transformed_fnorms; /* num_tris * 3 */
static int *screen_xy;          /* num_verts * 2 */
static signed char *visible;    /* num_verts */
static unsigned short *zbuffer;
static int num_tris, num_verts;

static void setup(void)
{
  cube = polyhedron_create(POLYHEDRON_CUBE, 0, 0, 0);
  texture = texture_load(ASSET_MARBLE_BMP);
  num_tris = cube->num_triangles;
  num_verts = cube->num_vertices;
  transformed = (int *)malloc(num_verts * 3 * sizeof(int));
  transformed_fnorms = (int *)malloc(num_tris * 3 * sizeof(int));
  screen_xy = (int *)malloc(num_verts * 2 * sizeof(int));
  visible = (signed char *)malloc(num_verts);
  zbuffer = (unsigned short *)malloc(VGA_SIZE * sizeof(unsigned short));
}

static void init(const RenderContext *ctx)
{
  (void)ctx;
  /* Use the texture's own palette so the marble renders correctly. */
  palette_apply(&texture->palette);
}

static void shutdown(void)
{
  model_free(cube);
  cube = NULL;
  texture_free(texture);
  texture = NULL;
  free(transformed);
  transformed = NULL;
  free(transformed_fnorms);
  transformed_fnorms = NULL;
  free(screen_xy);
  screen_xy = NULL;
  free(visible);
  visible = NULL;
  free(zbuffer);
  zbuffer = NULL;
}

static void render(const RenderContext *ctx)
{
  unsigned char *backbuffer = ctx->backbuffer;
  unsigned char ay = (unsigned char)ctx->frame;
  unsigned char ax = (unsigned char)(ctx->frame >> 1);
  const int *indices = cube->indices;
  const int *uvs = cube->uvs;
  int i;

  memset(backbuffer, 0, VGA_SIZE);
  transform_points(transformed, cube->positions, num_verts, ay, ax,
                   camera.cam_z);
  transform_dirs(transformed_fnorms, cube->face_normals, num_tris, ay, ax);
  project_points(&camera, transformed, num_verts, screen_xy, visible);
  memset(zbuffer, 0, VGA_SIZE * sizeof(unsigned short));

  for (i = 0; i < num_tris; i++)
  {
    int i0 = indices[i * 3 + 0];
    int i1 = indices[i * 3 + 1];
    int i2 = indices[i * 3 + 2];
    int *v0 = transformed + i0 * 3;
    int *v1 = transformed + i1 * 3;
    int *v2 = transformed + i2 * 3;
    int *nr = transformed_fnorms + i * 3;

    if (backface3d(nr, v0))
      continue;
    if (!visible[i0] || !visible[i1] || !visible[i2])
      continue;

    fill_triangle_textured(backbuffer, zbuffer,
        screen_xy[i0 * 2], screen_xy[i0 * 2 + 1], v0[2],
        uvs[i0 * 2], uvs[i0 * 2 + 1],
        screen_xy[i1 * 2], screen_xy[i1 * 2 + 1], v1[2],
        uvs[i1 * 2], uvs[i1 * 2 + 1],
        screen_xy[i2 * 2], screen_xy[i2 * 2 + 1], v2[2],
        uvs[i2 * 2], uvs[i2 * 2 + 1],
        texture);
  }

  font_draw(&font_default, backbuffer, 4, 4, 255, "textured_cube.c");

  vga_vsync();
  vga_blit(backbuffer);
}

const Scene textured_cube_scene = {setup, init, shutdown, render};
