/*
 * Affine texture-mapped cube generated by polyhedron_create().
 * The marble texture's own palette is uploaded in init() so the
 * cube renders with the correct colours.
 */

#include "textured_cube.h"

#include "../assets.h"
#include "utils/font.h"
#include "utils/math.h"
#include "utils/model.h"
#include "utils/palette.h"
#include "utils/polyhedron.h"
#include "utils/render3d.h"

#include <stdlib.h>
#include <string.h>
#include <vga.h>

static const Camera3D camera = {
    INT_TO_FP(4),    /* cam_z */
    FP_ONE >> 2,     /* near_z */
    INT_TO_FP(220),  /* proj_scale */
    160, 100         /* cx, cy */
};

static Model *cube;
static Texture *marble;
static int *transformed;        /* num_tris * 9 (positions) */
static int *transformed_fnorms; /* num_tris * 3 (face normals, for cull) */
static unsigned short *zbuffer;
static int num_tris;

static void setup(void)
{
  cube = polyhedron_create(POLYHEDRON_CUBE, 0, 0);
  marble = texture_load(ASSET_MARBLE_BMP);
  num_tris = cube->num_triangles;
  transformed = (int *)malloc(num_tris * 9 * sizeof(int));
  transformed_fnorms = (int *)malloc(num_tris * 3 * sizeof(int));
  zbuffer = (unsigned short *)malloc(VGA_SIZE * sizeof(unsigned short));
}

static void init(const RenderContext *ctx)
{
  (void)ctx;
  /* Use the texture's own palette so the marble renders correctly. */
  palette_apply(&marble->palette);
}

static void shutdown(void)
{
  model_free(cube);
  cube = NULL;
  texture_free(marble);
  marble = NULL;
  free(transformed);
  transformed = NULL;
  free(transformed_fnorms);
  transformed_fnorms = NULL;
  free(zbuffer);
  zbuffer = NULL;
}

static void render(const RenderContext *ctx)
{
  unsigned char *backbuffer = ctx->backbuffer;
  unsigned char ay = (unsigned char)ctx->frame;
  unsigned char ax = (unsigned char)(ctx->frame >> 1);
  int i;

  memset(backbuffer, 0, VGA_SIZE);
  transform_points(transformed, cube->positions, num_tris * 3, ay, ax,
                   camera.cam_z);
  transform_dirs(transformed_fnorms, cube->face_normals, num_tris, ay, ax);
  memset(zbuffer, 0, VGA_SIZE * sizeof(unsigned short));

  for (i = 0; i < num_tris; i++)
  {
    int *v = transformed + i * 9;
    int *nr = transformed_fnorms + i * 3;
    int *uv = cube->uvs + i * 6;
    int sx0, sy0, sx1, sy1, sx2, sy2;

    if (backface3d(nr, v))
      continue;

    if (!project3d(&camera, v[0], v[1], v[2], &sx0, &sy0) ||
        !project3d(&camera, v[3], v[4], v[5], &sx1, &sy1) ||
        !project3d(&camera, v[6], v[7], v[8], &sx2, &sy2))
      continue;

    fill_triangle_textured(backbuffer, zbuffer,
                           sx0, sy0, v[2], uv[0], uv[1],
                           sx1, sy1, v[5], uv[2], uv[3],
                           sx2, sy2, v[8], uv[4], uv[5],
                           marble);
  }

  font_draw(&font_default, backbuffer, 4, 4, 255, "textured_cube.c");

  vga_vsync();
  vga_blit(backbuffer);
}

const Scene textured_cube_scene = {setup, init, shutdown, render};
