#ifndef TIMING_H
#define TIMING_H

/* Calculate duration in milliseconds from XM timing parameters.
 * bpm:   tempo (beats per minute)
 * speed: ticks per row
 * rows:  number of rows
 */
#define XM_MS(bpm, speed, rows) \
  ((unsigned long)(rows) * (speed) * 2500UL / (bpm))

/* Convert a scene-local frame counter (~60 Hz, as passed to Scene.render)
 * to milliseconds. Approximate inverse of scene.c's ms→frame conversion. */
#define FRAME_MS(frame) ((unsigned long)(frame) * 1000UL / 60UL)

/*
 * Track playback position in a frame array generated by xm_sample_frames.py.
 *
 * Usage:
 *   static SampleTrack kick = SAMPLE_TRACK(kick_frames, KICK_FRAMES_COUNT);
 *
 *   if (sample_triggered(&kick, timeline_frame))
 *     // kick drum hit this frame
 */
typedef struct
{
  const unsigned int *frames;
  int count;
  int index;
} SampleTrack;

#define SAMPLE_TRACK(arr, n) { (arr), (n), -1 }

static inline int sample_triggered(SampleTrack *t, unsigned int timeline_frame)
{
  int next = t->index + 1;
  if (next < t->count && timeline_frame >= t->frames[next])
  {
    t->index = next;
    return 1;
  }
  return 0;
}

#endif
