#ifndef TIMING_H
#define TIMING_H

/* Duration in milliseconds for `rows` XM tracker rows at the given
 * tempo (`bpm` beats/min) and speed (`speed` ticks/row). */
#define XM_MS(bpm, speed, rows) \
  ((unsigned long)(rows) * (speed) * 2500UL / (bpm))

/* Convert a scene-local 60 Hz frame counter to milliseconds. */
#define FRAME_MS(frame) ((unsigned long)(frame) * 1000UL / 60UL)

/*
 * Playback cursor over a sorted frame array (typically generated by
 * tools/xm_sample_frames.py). Each call to sample_triggered() returns
 * 1 exactly once when `timeline_frame` first reaches or passes the
 * next entry in the array.
 */
typedef struct
{
  const unsigned int *frames;
  int count;
  int index;
} SampleTrack;

#define SAMPLE_TRACK(arr, n) { (arr), (n), -1 }

static inline int sample_triggered(SampleTrack *t, unsigned int timeline_frame)
{
  int next = t->index + 1;
  if (next < t->count && timeline_frame >= t->frames[next])
  {
    t->index = next;
    return 1;
  }
  return 0;
}

#endif
