#!/usr/bin/env python3
"""
Pack asset files into a single demo.dat and generate a C header
with offset/length constants for each asset.

Usage: python3 tools/pack_assets.py <build_dir> <src_dir> <asset_file> [<asset_file> ...]

Generates:
  <build_dir>/demo.dat   - concatenated asset data
  <src_dir>/assets.h     - #defines for ASSET_<NAME>_OFFSET and ASSET_<NAME>_LENGTH
"""

import os
import sys


def sanitize_name(filename):
    """Convert filename to a valid C identifier: HELLO_BMP, MUSIC_XM, etc."""
    name = os.path.basename(filename).upper()
    name = name.replace('.', '_').replace('-', '_').replace(' ', '_')
    return name


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <build_dir> <src_dir> <asset_file> ...", file=sys.stderr)
        sys.exit(1)

    build_dir = sys.argv[1]
    src_dir = sys.argv[2]
    asset_files = sys.argv[3:]

    dat_path = os.path.join(build_dir, "demo.dat")
    header_path = os.path.join(src_dir, "assets.h")

    entries = []
    offset = 0

    with open(dat_path, "wb") as dat:
        for path in asset_files:
            with open(path, "rb") as f:
                data = f.read()
            dat.write(data)
            name = sanitize_name(path)
            entries.append((name, offset, len(data)))
            offset += len(data)

    with open(header_path, "w") as h:
        h.write("/* Generated by pack_assets.py - do not edit */\n")
        h.write("#ifndef ASSETS_H\n")
        h.write("#define ASSETS_H\n\n")
        h.write(f'#define ASSET_DAT_FILE "demo.dat"\n\n')
        h.write("typedef struct {\n")
        h.write("    unsigned long offset;\n")
        h.write("    unsigned long length;\n")
        h.write("} Asset;\n\n")
        for name, off, length in entries:
            h.write(f"static const Asset ASSET_{name} = {{ {off}UL, {length}UL }};\n\n")
        h.write("#endif\n")

    print(f"Packed {len(entries)} assets into {dat_path} ({offset} bytes)")
    for name, off, length in entries:
        print(f"  {name}: offset={off}, length={length}")


if __name__ == "__main__":
    main()
